# Generated by Django 3.0.5 on 2020-08-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200807_1033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together={('name', 'slug')},
        ),
    ]
