# Generated by Django 3.0.5 on 2020-08-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200807_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together=set(),
        ),
    ]
